name = "libro-obras"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LIBRO_OBRAS"
id = "c91b22408fa44b808e5993dab3db6c70"

# Para dev local:
# [[kv_namespaces]]
# binding = "LIBRO_OBRAS"
# id = "c91b22408fa44b808e5993dab3db6c70"
# preview_id = "REEMPLAZA_CON_TU_KV_PREVIEW_ID"

